export const apiPaths = {
  health: '/health',
  agentRun: '/agent/run',
  agentRunUpload: '/agent/run/upload',
  agentAttachments: '/agent/attachments',
  agentStatus: (id: string) => `/agent/status/${id}`,
  agentActivity: (id: string) => `/agent/activity/${id}`,
  agentEvents: (id: string) => `/agent/events/${id}`,
  agentResume: (id: string) => `/agent/resume/${id}`,
  agentContinue: (id: string) => `/agent/continue/${id}`,
  agentExportPdf: (id: string) => `/agent/export/${id}/pdf`,
  clients: '/agent/clients',
  clientDetail: (id: string) => `/agent/clients/${id}`,
  clientResources: (id: string) => `/agent/clients/${id}/resources`,
  clientResourceUpload: (id: string) => `/agent/clients/${id}/resources/upload`,
  clientResourceDetail: (clientId: string, resourceId: string) =>
    `/agent/clients/${clientId}/resources/${resourceId}`,
  clientResourceRefresh: (clientId: string, resourceId: string) =>
    `/agent/clients/${clientId}/resources/${resourceId}/refresh`,
  clientArtifacts: (id: string) => `/agent/clients/${id}/artifacts`,
  settings: '/agent/settings',
  settingsReset: '/agent/settings/reset',
  conversations: '/agent/conversations',
  conversationMessages: (id: string) => `/agent/conversations/${id}/messages`,
  conversationDelete: (id: string) => `/agent/conversations/${id}`,
} as const
